databases:
  - name: idle2_DB
    databaseName: idle2_db
    user: idle2
    region: singapore

services:
  - type: web
    name: idle2
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: idle2_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

